# Generated by Django 5.1.2 on 2024-11-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
